title: Laravel Starter Kit (Inertia & React) Template
authors:
  - Jigar Dhulla
description: Ultra-strict, type-safe Laravel skeleton with Inertia & React, adapted for Spin. Includes MySQL, Queue, and Scheduler support.
repository: https://github.com/webjackl/spin-template-laravel-inertia-react
issues: https://github.com/webjackl/spin-template-laravel-inertia-react/issues